apiVersion: v1
kind: ConfigMap

metadata:
  name: backend-config

data:
  MONGO_HOST: "mongo-clusterip"
  MONGO_PORT: "27017"
  MONGO_DB: "db"
  APP_PORT: "5000"
  REDIS_HOST: "redis-clusterip"
  REDIS_PORT: "6379"
  NODE_ENV: "production"